# Generated by Django 4.2.7 on 2024-07-03 10:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tempdata", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attacklog",
            name="password",
        ),
    ]
