# Generated by Django 4.2.7 on 2024-07-18 09:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tempdata", "0002_remove_attacklog_password"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attacklog",
            name="username",
        ),
    ]
